version: '1.0'
services:
#  client-backend:
#    image: bookslist:0.0.1
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - '8080:8080'
#    depends_on:
#      - service-db
#    environment:
#      - SERVER_PORT=8080
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://service-db/books
#    restart: unless-stopped

  service-db:
    image: postgres:16.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - '15432:5432'
    volumes:
      - ./src/main/resources/db/migration/db.changelog-v1-create-database-books.sql:/docker-entrypoint-initdb.d/db.changelog-v1-create-database-books.sql
#      - db-data:/var/lib/postgresql/data
    restart: unless-stopped